### ISSUE TITLE
Variable dimensions are incompatible while calculating l1_loss(during Large-Scale_Training)

### ISSUE THREAD

**Issue by HyZhu39** [JWSoh/MZSR#19]
First, error message:
Traceback (most recent call last):
  File ".../Large-Scale_Training/main.py", line 49, in <module>
    main()
  File ".../Large-Scale_Training/main.py", line 46, in main
    Trainer.run()
  File "...\Large-Scale_Training\train.py", line 39, in run
    self.calc_loss()
  File "...\Large-Scale_Training\train.py", line 33, in calc_loss
    self.loss=tf.losses.absolute_difference(self.MODEL.output , self.label)
  File "...\lib\site-packages\tensorflow\python\ops\losses\losses_impl.py", line 271, in absolute_difference
    predictions.get_shape().assert_is_compatible_with(labels.get_shape())
  File "...\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 844, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (?, 96, 96, 3) and (?, 48, 48, 3) are incompatible

The cause of the error is that the parameter settings of the model itself cannot make the patch read in the dataset reach the size of the scale demanded, but remain the size itself unchanged, which leads to a mismatch in the dimension when calculating the l1_loss of the output of the model and ground truth.
So, I am curious, to get the experimental results proposed in the paper, how should the data be preprocessed in Large-Scale_Training.

**Comment by JWSoh** [comment]
We fixed the error in the code.
